name: Docker Example
on:
  push:
    branches:
      - main

jobs:
  checkout-step:
    runs-on: ubuntu-latest
    steps:
# Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js and install dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Npm
      - name: Install dependencies
        run:  |
          npm install
          npm run build --if-present
          npm test -- --coverage

      # step 5: Zip 
      - name: Make zip
        uses: actions/upload-artifact@v5
        with:
          name: my-apps
          path: .
      - name: Code Coverage Report
        uses: mridang/action-test-reporter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: ./coverage/clover.xml
          working-directory: ./
  
      # Step 6: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Step 7: Build and push Docker container
      - name: Build and push Docker container
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dev-ops:latest


          
